// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bewsjtvxgokozozffemk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJld3NqdHZ4Z29rb3pvemZmZW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzEwMzUsImV4cCI6MjA3MjIwNzAzNX0.rbvyvTnQDrxp4W8hRF5jlM9k5IZ3WIo-Q0x613YN1bQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});